#ifndef CODES_HEADER
#define CODES_HEADER

/* ERROR CODES */
#define UNEXPECTED_ERROR    -1
#define MAIN_NOT_FOUND      1
#define DUPLICATE_FUN_NAME  2
#define TYPE_ERROR          3
#define FUNCTION_NOT_FOUND  4
#define VAR_REDECLARATION   5
#define VAR_NOT_DECLARED    6
#define RETURN_NOT_FOUND    7
#define AR_NOT_INITIALIZED  8

/* STACK CODES */
#define AR_TYPE_OFFSET      10
#define PAUSE_CODE          -1
#define INT_CODE            1
#define STRING_CODE         2
#define VOID_CODE           3
#define BOOL_CODE           4
#define DOUBLE_CODE         5
#define CHAR_CODE           6
#define IDENT_CODE          7
#define AR_INT_CODE         11
#define AR_STRING_CODE      12
#define AR_VOID_CODE        13
#define AR_BOOL_CODE        14

#endif /* CODES_HEADER */