#ifndef CODES_HEADER
#define CODES_HEADER

/* ERROR CODES */
#define UNEXPECTED_ERROR    -1
#define MAIN_NOT_FOUND      1
#define DUPLICATE_FUN_NAME  2
#define TYPE_ERROR          3
#define FUNCTION_NOT_FOUND  4
#define VAR_REDECLARATION   5
#define VAR_NOT_DECLARED    6
#define RETURN_NOT_FOUND    7

/* STACK CODES */
#define PAUSE_CODE          -1
#define INT_CODE            1
#define STRING_CODE         2
#define VOID_CODE           3
#define BOOL_CODE           4
#define DOUBLE_CODE         5
#define CHAR_CODE           6
#define IDENT_CODE          7

#endif /* CODES_HEADER */