/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <iostream>
#include <fstream>
#include <filesystem>
#include "Parser.H"
#include "Absyn.H"
#include "Analyser.H"
#include "Compiler.H"

void usage() {
  printf("usage: latc_86_64 inputFilePath\n");
}

int main(int argc, char ** argv) {
  FILE *input, *libFun;
  Analyser *analyser;
  Compiler *compiler;
  char *inputFilename = NULL;
  bool noExtensions = false;

  if (argc == 2) {
    inputFilename = argv[1];
    input = fopen(inputFilename, "r");
    if (!input) {
      usage();
      exit(1);
    }
  }
  else {
    usage();
    exit(1);
  }

  std::string inputFilenameStr = std::string(inputFilename);
  std::string outputFilename = inputFilenameStr.substr(0, inputFilenameStr.find_last_of('.'));
  if (outputFilename.empty()) {
    noExtensions = true;
    outputFilename = inputFilenameStr;
  }
  std::ofstream output(outputFilename + ".s");

  /* Parse lib functions */
  libFun = fopen("lib/predefinedFunctions.txt", "r");
  if (!libFun) {
    fprintf(stderr, "ERROR\nCouldn't find file \'lib/predefinedFunctions.txt\'\n");
    exit(1);
  }
  Program *parsed_lib = pProgram(libFun);

  Program *parse_tree = pProgram(input);
  if (parse_tree) {
    analyser = new Analyser();
    analyser->analyseProgram(parse_tree, parsed_lib);
    //printf("\nCode check succesful!\n\n");
    
    compiler = new Compiler();
    //printf("\n\nCompiler result:\n");
    output << compiler->compile(parse_tree, parsed_lib);
    output.close();

    system(("gcc -m64 " + outputFilename + ".s lib/runtime.o -o " + outputFilename + (noExtensions ? "latc" : "")).c_str());

    fprintf(stderr, "OK\n");    
    return 0;
  }
  return 1;
}

