/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <stdio.h>
#include <string.h>
#include <string>
#include <iostream>
#include "Parser.H"
#include "Printer.H"
#include "Absyn.H"
#include "Analyser.H"
#include "Compiler.H"

void usage() {
  printf("usage: Call with one of the following argument combinations:\n");
  printf("\t--help\t\tDisplay this help message.\n");
  printf("\t(no arguments)	Parse stdin verbosely.\n");
  printf("\t(files)\t\tParse content of files verbosely.\n");
  printf("\t-s (files)\tSilent mode. Parse content of files silently.\n");
}

int main(int argc, char ** argv) {
  FILE *input, *libFun;
  Analyser *analyser;
  Compiler *compiler;
  int quiet = 1;
  char *filename = NULL;
  std::string output;

  if (argc > 1) {
    if (strcmp(argv[1], "-s") == 0) {
      quiet = 1;
      if (argc > 2) {
        filename = argv[2];
      } else {
        input = stdin;
      }
    } else {
      filename = argv[1];
    }
  }

  if (filename) {
    input = fopen(filename, "r");
    if (!input) {
      usage();
      exit(1);
    }
  } else input = stdin;

  /* Parse lib functions */
  libFun = fopen("lib/predefinedFunctions.txt", "r");
  if (!libFun) {
    printf("ERROR\nCouldn't find file \'lib/predefinedFunctions.txt\'\n");
    exit(1);
  }
  Program *parsed_lib = pProgram(libFun);

  Program *parse_tree = pProgram(input);
  if (parse_tree) {
    analyser = new Analyser();
    analyser->analyseProgram(parse_tree, parsed_lib);
    //printf("\nCode check succesful!\n\n");
    
    compiler = new Compiler();
    //printf("\n\nCompiler result:\n");
    std::cout << compiler->compile(parse_tree, parsed_lib);
    
    //printf("\nParse Succesful!\n");
    if (!quiet) {
      printf("\n[Abstract Syntax]\n");
      ShowAbsyn *s = new ShowAbsyn();
      printf("%s\n\n", s->show(parse_tree));
      printf("[Linearized Tree]\n");
      PrintAbsyn *p = new PrintAbsyn();
      printf("%s\n\n", p->print(parse_tree));
    }
    return 0;
  }
  return 1;
}

